/**
 * The module definition for the MainApp for the cis-template application. This includes all the dependencies that are required by the system.
 *
 * Applied Styles: [Y001, Y002, Y010, Y020, Y021, Y023]
 */
(function() {
    angular
        .module('cid', [
            'ui.router',
            //'ngMaterial',
            'ui.bootstrap',
            'ui.timepicker',
            'tableSort',

            // Dependencies
            'cid.app.constants',
            'cid.app.variables',
            'cid.app.config',
            'cid.app.environment',
            'cid.user-settings',
            'cid.data',
            'cid.staff-data',
            'cid.interim-reports',
            'ContactsTableDirective',
            'cid.search',
            'Lookups',
            'SelectionBoxes',
            'Filters',

            'cid.system.collapsible',

            // Core Services
            'ErrorHandler',
            'cid.core.authentication',

            // Main Modules
            'cid.site',
            'cid.tests',

            'cid.exams',

            'cid.admissions',
            'cid.student-record',
            'cid.course-record-viewer',
            'cid.ilp-letters',
            'StudentEmailer',

            // General Directives
            'ReportLinkDirective',
            'CurrentYearSelectorDirective',

            //AddressLookup
            'AddressLookupDirective',

            // Read-Only Directive Definitions
            'AddressDetailsDirective',
            'ContactsTableDirective',
            'CourseSearchDirective',
            'CoursesTableDirective',
            'CourseGroupsTableDirective',
            'EnrolmentsTableDirective',
            'StudentEntryQualificationsTableDirective',
            'PersonContactDetailsDirective',
            'PersonContactDetailsLookupDirective',
            'PersonDetailsDirective',
            'PersonDetailsLookupDirective',
            'StudentSummaryDirective',
            'StudentImageDirective',
            'StudentDetailsDirective',
            'StudentDetailsLookupDirective',
            'RegistersTableDirective',
            'CorrespondenceTableDirective',
            'ILPInterviewsTableDirective',
            'StudentWarningDetailsDirective',
            'StudentSpecialCategoryDetailsDirective',
            'StudentYearDetailsDirective',
            'StudentTimetableDirective',
            'ExternalResultsArchiveTableDirective',
            'StudentInterimReportsTableDirective',
            'StudentLearningSupportDetailsDirective',
            'StudentCourseSupportTypesEditorDirective',
            'CollegeFundPaymentDetailsDirective',
            'WordGeneratorDirective',
            'StudentOverallAttendanceDetailsDirective',
            'StudentAdmissionsDetailsDirective',
            'MedicalNotesDetailsDirective',
            'TutorGroupRemarkPermissionTableDirective',
            'ExamResultsTableDirective',
            'OptionEntriesDirective',
            'WarningCodeChangeDetailsDirective',
            'NoteTableDirective',
            'EnrolmentsTableDirective',
            'TimetableTableDirective',
            'StudentConcessionTableDirective',
            'StudentLLDDHealthProblemCategoryTableDirective',
            'StudentSafetyPlanViewerDirective',
            'StudentRiskLevelDetailsDirective',
            'StudentPredictedGradesTableDirective',
            'PastoralMonitorDetailsDirective',

            'StaffAbsenceTableDirective',

            'StudentFilesDirective',
            'StudentFilesUploaderDirective',
            // Editor Directives
            'AddressEditorDirective',
            'AcademicYearsEditorDirective',
            'ApplicationStatusesEditorDirective',
            'ContactsEditorDirective',
            'EnrolmentManagerDirective', // This is the dynamic checker version
            'EnrolmentsEditorDirective', // This is the table editing version (not is working order)
            'StudentEntryQualificationsEditorDirective',
            'RegistersEditorDirective',
            'StudentSpecialCategoryEditorDirective',
            'StudentRiskLevelEditorDirective',
            'PersonEditorDirective',
            'StudentWarningEditorDirective',
            'StudentBursaryEditorDirective',
            'StudentWithdrawalDirective',
            'StudentYearEditorDirective',
            'CourseDetailsDirective',
            'CollegeFundPaymentEditorDirective',
            'StudentSummaryEditorDirective',
            'StudentContactPreferencesEditorDirective',
            'MedicalNotesEditorDirective',
            'ExamResultsEditorDirective',
            'RoomsEditorDirective',
            'BlocksEditorDirective',
            'PeriodsEditorDirective',
            'TutorGroupsEditorDirective',
            'FacultiesEditorDirective',
            'DepartmentsEditorDirective',
            'SubjectsEditorDirective',
            'LevelsEditorDirective',
            'YearGroupsEditorDirective',
            'SchoolsEditorDirective',
            'AdmissionsDirective',
            'SettingsEditorDirective',
            'TextLookupEditorDirective',
            'LetterTemplateEditorDirective',
            'PossibleGradesEditorDirective',
            'PossibleGradeSetsEditorDirective',
            'StaffsEditorDirective',
            'SpecialCategoriesEditorDirective',
            'HolidaysEditorDirective',
            'AttendanceMonitoringsEditorDirective',
            'CentralMonitoringsEditorDirective',
            'PunctualityMonitoringsEditorDirective',
            'PersonCardEditorDirective',
            'ReferralReasonsEditorDirective',
            'ConcessionTypesEditorDirective',
            'SupportTypesEditorDirective',
            'OfferTypesEditorDirective',
            'EntryQualificationTypesEditorDirective',
            'ReportingPeriodsEditorDirective',
            'RiskLevelsEditorDirective',
            'EntryQualificationsEditorDirective',
            'StudentLearningSupportCostsEditorDirective',
            'StudentLearningSupportVisitsEditorDirective',
            'StudentLearningSupportEditorDirective',
            'RolesEditorDirective',
            'PersonNotesEditorDirective',
            'ILPInterviewsEditorDirective',
            'StudentLLDDHealthProblemCategoryEditorDirective',
            'CourseEditorDirective',
            'StudentRiskAssessmentEditorDirective',
            'StudentSafetyPlanEditorDirective',
            'ILPLetterEditorDirective',
            'StudentWorkPlacementsEditorDirective',
            'StudentInterimReportsEditorDirective',
            'RequestEditorDirective',
            'LetterTypesEditorDirective',
            'CorrespondenceTypesEditorDirective',
            'StatementBankTypesEditorDirective',
            'StatementBanksEditorDirective',
            'InterviewTypesEditorDirective',
            'StudentCareersRecordsEditorDirective',
            'bulk-careers-record',
            'dialogs-edit-interim-reports-due',
            'StudentConcessionEditorDirective',
            'StudentVolunteeringLogsEditorDirective',
            'StudentDukeOfEdinburghsEditorDirective',
            'SchoolReferencesDetailsDirective',
            //cristal
            'CristalRoomsEditorDirective',
            'MyInterimReportsTableDirective',
            //exams
            'ExamBoardsEditorDirective',
            'ExamSeriesEditorDirective',
            'SyllabusDetailsDirective',
            'PastoralMonitorEditorDirective'

        ]);

})();
